CREATE PROCEDURE sp_CreateUser
    @Name NVARCHAR(100),
    @Surname NVARCHAR(100),
    @UserName NVARCHAR(100),
    @PlainPassword NVARCHAR(200),
    @TenantId INT,
    @UserId INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @Salt VARBINARY(32) = CRYPT_GEN_RANDOM(32);
    DECLARE @Hash VARBINARY(64) = HASHBYTES('SHA2_256', @Salt + CAST(@PlainPassword AS VARBINARY(200)));

    INSERT INTO [USER] (NAME, SURNAME, USERNAME, HASHPASSWORD, SALTPASSWORD, TENANTID)
    VALUES (@Name, @Surname, @UserName, @Hash, @Salt, @TenantId);

    SET @UserId = SCOPE_IDENTITY();
END

